version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - ../:/var/www/html/
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=password9
      - MYSQL_DATABASE=pokemonstore
    depends_on:
      - db
    networks:
      - pokemonstore_net
      
  db:
    image: mysql:8.0
    container_name: pokemonstore_db
    environment:
      MYSQL_ROOT_PASSWORD: password9
      MYSQL_DATABASE: pokemonstore
      TZ: Europe/Helsinki
    ports:
      - "6034:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./pokemonstore.sql:/docker-entrypoint-initdb.d/01-pokemonstore.sql
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-time-zone=Europe/Helsinki
    networks:
      - pokemonstore_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pokemonstore_phpmyadmin
    depends_on:
      - db
    ports:
      - "82:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password9
      MYSQL_ROOT_PASSWORD: password9
      TZ: Europe/Helsinki
    networks:
      - pokemonstore_net

volumes:
  mysql_data:

networks:
  pokemonstore_net:
    driver: bridge
  